name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y just
    - name: Build
      run: just build
    - name: Run tests
      run: just test
    - name: Run clippy
      run: just clippy
    - name: Run bench
      run: just bench
